# src: /shared/configs/secretlint.config.yaml
# @(#) : secretlintrc
#
# Copyright (c) 2025 atsushifx <http://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

rules:
  - id: "@secretlint/secretlint-rule-preset-recommend"
